### ISSUE TITLE
Include list/whitelist for files to check by RuboCop

### ISSUE THREAD

**Issue by eregon** [rubocop-hq/rubocop#4961]
It seems currently RuboCop always scans every `.rb`/`#!ruby` file under the current directory if not explictly passed filenames on the command-line.

In the config, `Include` seems only useful to add non-`.rb` files (more like "extra files" to scan), and is not really related to `Exclude` ("ignore those files when `$ rubocop` is invoked").

What I want is to be able to tell, in my RuboCop `.rubocop.yml` config, which files to check.
So for instance, I want to check everything under `lib/` and `bin/`, but nothing else.
This is particularly useful in projects where some of the Ruby files are imported form other projects (so modifying them for style is not an option), or where incrementally transitioning a code base to be checked by RuboCop.
A real-world example of this can be seen in [TruffleRuby's RuboCop config](https://github.com/graalvm/truffleruby/blob/d9abd33980da0c6eee0f8cede98f85e64ab1b4f2/.rubocop.yml).

Currently, whitelisting files/dirs seems only possible if I pass the list to rubocop directly:
```bash
$ rubocop lib bin
```
But not in the configuration file.
This quickly becomes cumbersome as this list grows or becomes more complex.
And it forces me to have the list of files checked by RuboCop *outside* the RuboCop config.

Currently I am working around by having a very long `Exclude` list, but this feels wrong, because I want to specify what files are checked by RuboCop, not every other file/dir in the repo.

Is there a way I missed to achieve what I want?
If not, do you think this feature would be worth adding to RuboCop?

## RuboCop version

```
$ rubocop -V
0.51.0 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-linux)
```

**Comment by eregon** [comment]
Note that something like:
```yaml
AllCops:
  Exclude:
    - '**/*.rb'
  Include:
    - 'bin/**/*.rb'
    - 'lib/**/*.rb'
```
does not work and checks no files.

**Comment by eregon** [comment]
One way to implement this might be to have something like
`CheckFilesInCurrentDirectoryByDefault: false` and then in `Include` specify which files to check.

**Comment by bbatsov** [comment]
We've removed the hardcoded default includes a few version ago, so your problem should be solved now.

**Comment by MatheusRich** [comment]
> Note that something like:
> 
> ```yaml
> AllCops:
>   Exclude:
>     - '**/*.rb'
>   Include:
>     - 'bin/**/*.rb'
>     - 'lib/**/*.rb'
> ```
> 
> does not work and checks no files.

Is it possible to achieve something similar to this in Rubocop?

**Comment by MatheusRich** [comment]
> Note that something like:
> 
> ```yaml
> AllCops:
>   Exclude:
>     - '**/*.rb'
>   Include:
>     - 'bin/**/*.rb'
>     - 'lib/**/*.rb'
> ```
> 
> does not work and checks no files.

@bbatsov Is it possible to achieve something similar to this in Rubocop?

**Comment by bobf** [comment]
@MatheusRich @bbatsov I would also like this feature. I would expect `Include` to override `Exclude` (or at least raise an error/warning).

My use case is I have a file in my `bin/` directory that I manage but all other files I do not want to touch.

I would happily put a pull request forward if there is a chance it would be merged !

**Comment by eregon** [comment]
@bbatsov For some reason I missed your comment above.
`Include` seems to still not work with RuboCop 0.79.0.
Could you reopen this issue?

For instance, just this:
```
AllCops:
  Include:
    - 'lib/**/*.rb'
```
will report failures for some files under the `tool` directory, which should not be scanned.

This doesn't seem to change anything:
```
inherit_mode:
  override:
    - Include

AllCops:
  Include:
    - 'lib/**/*.rb'
```

That's running with `rubocop -c .rubocop.yml`.
Just using `rubocop` will pick up many other .rubocop.yml and then inspect too many files.

#5882 seems to be the PR allowing to override `Include`, but I can't figure out how to use it.
